# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brio < Formula
  desc "A vim-style TUI for Bruno API collections"
  homepage "https://github.com/luca-trifilio/brio"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.0/brio_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "602a3b7c54bebd1fb90180f639362f6f0d4784dcae9baf3777126a7802dd4b64"

      define_method(:install) do
        bin.install "brio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.0/brio_0.2.0_Darwin_arm64.tar.gz"
      sha256 "426bc96d08ff3a3fc7ef07da51fdb4f440658b42459ae3298b4a4173db481cc5"

      define_method(:install) do
        bin.install "brio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.0/brio_0.2.0_Linux_x86_64.tar.gz"
      sha256 "03ef28f2d9ba27aca4b24f657d4399562e11d3007494ac03809373b19541d4fe"
      define_method(:install) do
        bin.install "brio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.0/brio_0.2.0_Linux_arm64.tar.gz"
      sha256 "09b9fb48eb5582dd5c85a3ff56f6eaa3ff48b828ef21b533486dc180c737689a"
      define_method(:install) do
        bin.install "brio"
      end
    end
  end

  test do
    system "#{bin}/brio", "--version"
  end
end
