# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brio < Formula
  desc "A vim-style TUI for Bruno API collections"
  homepage "https://github.com/luca-trifilio/brio"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.1/brio_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "f6349951fa3a132a439708398ca5db39eea3522798a65196f44dddb3158cf88d"

      define_method(:install) do
        bin.install "brio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.1/brio_0.2.1_Darwin_arm64.tar.gz"
      sha256 "11d011331399d109fea3f0aeffc5c0f910c31e68107ea3d19154b07b221d1535"

      define_method(:install) do
        bin.install "brio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.1/brio_0.2.1_Linux_x86_64.tar.gz"
      sha256 "ebf2aad38bdc69d57147fd962c4eec82252b5850eaad148682c3d4805b321044"
      define_method(:install) do
        bin.install "brio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.1/brio_0.2.1_Linux_arm64.tar.gz"
      sha256 "b8d4c8d8f2cf03d2c23b6b5f3778cf994b841e893f6a13233098d48da7f39fcc"
      define_method(:install) do
        bin.install "brio"
      end
    end
  end

  test do
    system "#{bin}/brio", "--version"
  end
end
