# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brio < Formula
  desc "A vim-style TUI for Bruno API collections"
  homepage "https://github.com/luca-trifilio/brio"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.2/brio_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "be73ae7d121931106875a2b048d61bec988e1c3200865f587c8486e8fa0fda13"

      define_method(:install) do
        bin.install "brio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.2/brio_0.2.2_Darwin_arm64.tar.gz"
      sha256 "7c8f44bdfd16812cc8018cd09a260f0038b9e9582887ae2d0cc93e22b9bde2ca"

      define_method(:install) do
        bin.install "brio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.2/brio_0.2.2_Linux_x86_64.tar.gz"
      sha256 "e50f6541bbadfd1ad54e5751fe0c8c15bcacd5f9e5f458a0c23192eed4fd0c93"
      define_method(:install) do
        bin.install "brio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luca-trifilio/brio/releases/download/v0.2.2/brio_0.2.2_Linux_arm64.tar.gz"
      sha256 "96b13ed8f8af1af3feb3b85bec1515ff39ecf0e76d37190c5fca646882157e1d"
      define_method(:install) do
        bin.install "brio"
      end
    end
  end

  test do
    system "#{bin}/brio", "--version"
  end
end
